name: TypeCheck and Lint

on:
  push:
    branches:
      - main
      - dev
  pull_request:

permissions:
  contents: read

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout/releases/tag/v7.0.0
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0

      # https://github.com/pnpm/setup/releases#release-v2.1.0
      - uses: pnpm/setup@703c52620218391530e48b9e8870d5c0082e1b9b
        with:
          cache: true
          runtime: node@24

      - run: pnpm run lint

      - run: pnpm run build
